name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  cron:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - name: Run
        run: uv run hnbot
        env:
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          LOGFIRE_TOKEN: ${{ secrets.LOGFIRE_TOKEN }}
